# **Numpy One Dimension**

In [1]:
import numpy as np

In [2]:
num_array = np.array([1,2,3,4])
num_array

array([1, 2, 3, 4])

In [3]:
type(num_array)

numpy.ndarray

In [4]:
num_array[-1]

4

In [5]:
num_array.shape

(4,)

In [6]:
num_array.ndim

1

In [7]:
num_array.size

4

In [8]:
num_array.dtype

dtype('int64')

In [9]:
str_array = np.array([True, 10, 'abc', 5.5])

In [10]:
str_array.dtype.name

'str1024'

In [11]:
str_array.itemsize

128

In [12]:
obj_array = np.array([{'city': 'London'}, {'city': 'Boston'}])
obj_array

array([{'city': 'London'}, {'city': 'Boston'}], dtype=object)

In [13]:
obj_array.dtype.name

'object'

In [14]:
obj_array.itemsize

8

# Numpy Two Dİmensions

In [15]:
first = np.array([[1,2,3,4], [5,6,7,8]])
first

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
first.shape

(2, 4)

In [17]:
first.ndim

2

In [18]:
second = np.array([[9,10,11,12], [13,14,15,16]])
second

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
second.shape


(2, 4)

In [20]:
first + second

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [21]:
first + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [22]:
first - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [23]:
first / 3

array([[0.33333333, 0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333, 2.66666667]])

# Concatenation

In [24]:
np.concatenate([first, second])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
np.concatenate([first, second], axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [26]:
np.concatenate((np.array([1,2,3]), np.array([4,5,6])))

array([1, 2, 3, 4, 5, 6])

**Numpy Random**

In [27]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
np.ones((5, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
#Generate random floats
np.random.seed(10)
np.random.random((2, 3))

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])

**Methods randint, uniform & choice**

In [31]:
#Generate random integers
np.random.seed(15)
np.random.randint(10, 20, size=(2, 4))

array([[18, 15, 15, 17],
       [10, 17, 15, 16]])

In [32]:
#allows define the range.
np.random.seed(10)
np.random.uniform(10.0, 50.0, size=(3, 5))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 , 29.94028049],
       [18.99186582, 17.92251459, 40.42122849, 16.76443346, 13.53359257],
       [37.41439273, 48.13573385, 10.15793065, 30.48769054, 42.50483847]])

In [33]:
np.random.seed(10)
np.random.choice(np.array([1, 2, 3]), size=20)

array([2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 3, 1, 2, 1, 3, 1, 3, 1, 1])

In [34]:
np.random.seed(10)
np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10)


array(['e', 'u', 'a', 'e', 'o', 'u', 'e', 'a', 'e', 'i'], dtype='<U1')

**NumPy Arange & Reshape**

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(15, 25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [37]:
np.arange(20).reshape([2, 10])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [51]:
np.random.seed(10)
np.random.random(10,).reshape((2, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

**Method Flatten**






In [53]:
#flatten method in NumPy is used to convert an n-dimensional array into a 1-dimensional array.
np.random.seed(10)
np.random.randint(50, 80,(4, 3, 3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69])

In [57]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])